version: '3.8'

# Podman rootlessç”¨è¨­å®š - é«˜ãƒãƒ¼ãƒˆç‰ˆ
# 80/443ã®ä»£ã‚ã‚Šã«8080/8443ã‚’ä½¿ç”¨

services:
  # ç’°å¢ƒå¤‰æ•°åˆæœŸåŒ–ã‚µãƒ¼ãƒ“ã‚¹ï¼ˆä¸€åº¦ã ã‘å®Ÿè¡Œï¼‰
  init:
    image: docker.io/library/alpine:latest
    command: |
      sh -c '
        # å¿…è¦ãªãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«
        apk add --no-cache openssl;
        
        # ãƒ‰ãƒ¡ã‚¤ãƒ³åã®ç¢ºèª
        DOMAIN=$${DOMAIN:-};
        
        if [ ! -f /shared/.env.production ]; then
          echo "ðŸ” ç’°å¢ƒè¨­å®šãƒ•ã‚¡ã‚¤ãƒ«ã‚’ç”Ÿæˆä¸­...";
          DB_PASSWORD=$$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32);
          REDIS_PASSWORD=$$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32);
          JWT_SECRET=$$(openssl rand -base64 64 | tr -d "=+/" | cut -c1-64);
          
          # HTTPSè¨­å®š
          if [ -n "$$DOMAIN" ]; then
            echo "ðŸ”’ HTTPSè¨­å®šã‚’æœ‰åŠ¹åŒ–: $$DOMAIN";
            SSL_ENABLED=true;
            echo "ðŸ“‹ Let'\''s Encryptè¨¼æ˜Žæ›¸ã¯èµ·å‹•å¾Œã«å–å¾—ã•ã‚Œã¾ã™";
          else
            echo "ðŸŒ HTTPè¨­å®šã§èµ·å‹•ï¼ˆãƒ‰ãƒ¡ã‚¤ãƒ³æœªæŒ‡å®šï¼‰";
            SSL_ENABLED=false;
          fi
          
          cat > /shared/.env.production << EOF
      NODE_ENV=production
      PORT=3000
      DB_HOST=postgres
      DB_PORT=5432
      DB_USER=lazychillroom_user
      DB_PASSWORD=$$DB_PASSWORD
      DB_NAME=lazychillroom
      POSTGRES_USER=lazychillroom_user
      POSTGRES_PASSWORD=$$DB_PASSWORD
      POSTGRES_DB=lazychillroom
      REDIS_HOST=redis
      REDIS_PORT=6379
      REDIS_PASSWORD=$$REDIS_PASSWORD
      REDIS_DB=0
      JWT_SECRET=$$JWT_SECRET
      UPLOAD_PATH=./uploads
      MAX_FILE_SIZE=10485760
      ALLOWED_EXTENSIONS=jpg,jpeg,png,gif,webp,mp4,webm,pdf,txt,docx
      RATE_LIMIT_WINDOW_MS=60000
      RATE_LIMIT_MAX_REQUESTS=100
      BCRYPT_ROUNDS=12
      TRUST_PROXY=true
      SECURE_COOKIES=$$SSL_ENABLED
      SESSION_SECURE=$$SSL_ENABLED
      SSL_ENABLED=$$SSL_ENABLED
      DOMAIN=$$DOMAIN
      EOF
          echo "âœ… ç’°å¢ƒè¨­å®šãƒ•ã‚¡ã‚¤ãƒ«ç”Ÿæˆå®Œäº†";
          echo "ðŸ“‹ ç”Ÿæˆã•ã‚ŒãŸãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰:";
          echo "   DB: $$DB_PASSWORD";
          echo "   Redis: $$REDIS_PASSWORD";
          echo "   JWT: $${JWT_SECRET:0:20}...";
          if [ -n "$$DOMAIN" ]; then
            echo "ðŸ”’ HTTPS: æœ‰åŠ¹ ($$DOMAIN)";
          else
            echo "ðŸŒ HTTP: ãƒ­ãƒ¼ã‚«ãƒ«èµ·å‹•";
          fi
        else
          echo "âœ… ç’°å¢ƒè¨­å®šãƒ•ã‚¡ã‚¤ãƒ«ã¯æ—¢ã«å­˜åœ¨ã—ã¾ã™";
        fi
      '
    environment:
      - DOMAIN=${DOMAIN:-}
    volumes:
      - .:/shared
    restart: "no"

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - TRUST_PROXY=true
      - SECURE_COOKIES=true
      - SESSION_SECURE=true
    volumes:
      - ./uploads:/app/uploads
      - app_logs:/app/logs
    depends_on:
      init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:exec,nodev,nosuid,size=100m

  postgres:
    image: docker.io/library/postgres:15
    env_file:
      - .env.production
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./migrations/postgresql-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    depends_on:
      init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lazychillroom_user -d lazychillroom"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    security_opt:
      - no-new-privileges:true

  redis:
    image: docker.io/library/redis:7-alpine
    env_file:
      - .env.production
    command: |
      sh -c 'redis-server --requirepass "$$REDIS_PASSWORD" --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru'
    volumes:
      - redis_data:/data:Z
    depends_on:
      init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a \"$$REDIS_PASSWORD\" ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    security_opt:
      - no-new-privileges:true

  # Nginx (é«˜ãƒãƒ¼ãƒˆç‰ˆ)
  nginx:
    image: docker.io/library/nginx:alpine
    # é«˜ãƒãƒ¼ãƒˆç•ªå·ã‚’ä½¿ç”¨ï¼ˆrootlessç’°å¢ƒå¯¾å¿œï¼‰
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local
  nginx_logs:
    driver: local
